stages:
    - build
    - publish
    - deploy
    
services:
  - docker:dind
   
build:
    image: trion/ng-cli-karma
    stage: build
    script:
        - cd smart-campus
        - npm install
        - ./node_modules/@angular/cli/bin/ng build --aot --prod
        - rm -rf node_modules
        - dt=$(date '+%Y%m%d%H%M%S');
        - echo -n "$dt" > ../deployment/version
    artifacts:
        paths:
            - smart-campus/
            - deployment/

publish:
    image: docker:latest
    stage: publish
    script:
        - echo "Building docker image"
        - version=$(cat deployment/version)
        - cd smart-campus
        - docker login -u josedrojasa -p Hollowichigo428
        - docker build . -t josedrojasa/thesis-front:"$version"
        - docker push josedrojasa/thesis-front:"$version"

deploy:
    image: openshift/origin-cli
    stage: deploy
    script:
        - oc login "https://serveo.net:8444" --token="eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpb3QtZnJvbnQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ2l0bGFiLWNpLXRva2VuLTl0djlxIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImdpdGxhYi1jaSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQ2NGY3YTAyLTcxZjQtMTFlOS1iN2I1LTUyNTQwMDEwZTEwYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDppb3QtZnJvbnQ6Z2l0bGFiLWNpIn0.t5uGcGXcAZfuHKo1TdP-2sz4q7K1DFgxskR4bFUMgJwt02EJGCuCqjclz0C_Hzh7i_muVA-uWugDxpVLGmjuER449yIbueR9SNoqIO1iqqk1GHKJhuA5DQXZdxrEaKkhFP7FPmLLSGHpq9lIoJCEgLIrJTxBv8MaYX7cUkTy72Ud9PIFEzXM9k2YSDZluV6g-Vikx1Cm58r_cm23V7xXGHOdRvZEdj1O2caDMh4bQM4m9borpMuylKdhBOXI5oFc9_hzRXl0INuvpHbaKzAv7eDC8SsPQQrzsy7B1yVm-4s7bZPDjxeM2yW2mRy9W__UCaXsKnXX5uJUb9369R4nTQ" --insecure-skip-tls-verify
        - oc project iot-front
        - deployment1=$(cat deployment/deployment_1.yaml)
        - deployment2=$(cat deployment/deployment_2.yaml)
        - version=$(cat deployment/version)
        - echo -n "$deployment1" > deployment.yaml
        - echo "$version" >> deployment.yaml
        - echo "$deployment2" >> deployment.yaml
        - oc replace -f deployment.yaml