apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-microservice
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingParams:
      updatePeriodSeconds: 10
      intervalSeconds: 5
      timeoutSeconds: 120
  template:
    metadata:
      labels:
        app: admin-microservice
        version: v1
    spec:
      containers:
      - name: admin-microservice
        image: josedrojasa/admin-service:
